baseURL = "/"
title = "openEuler documentation"

disablePathToLower = true

# Site language. Available translations in the theme's `/i18n` directory.
languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

uglyURLs = true
buildFuture = true

# Define the number of posts per page
paginate = 10


[languages]

[languages.en]
    languageCode = "en"
    contentDir = "content/en"

[languages.zh]
    languageCode = "zh"
    contentDir = "content/zh"

[languages.ru]
    languageCode = "ru"
    contentDir = "content/ru"



[params]
    author = "openEuler"
    defaultKeywords = ["devows", "hugo", "go", "openEuler"]
    defaultDescription = "Site template made by devcows Modified by openEuler team"
    searchTitle = "openEuler Documentation"
    email = "contact@openeuler.org"
    
    ### DOC Configurations
    BookRepo = 'https://gitee.com/opengauss/docs/blob'
    BookEditPath= 'blob/master/content'
    BookDateFormat = 'Jan 2, 2019'
    enableGitInfo = true
    BookMenuBundle = '/menu'
    bookHidden = true
    bookFlatSection = true
    BookMenuBundleActiveLinkColor = '\#004ed0'

    languageZh = "中文"
    languageEn = "English"
    languageRu = "Русский"

    ltsText = "LTS"
    version_95 = "21.03"
    version_96 = "20.03 LTS SP1"
    version_97 = "20.03 LTS"
    version_98 = "20.09"

    navLink = "Documentation"

